services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 10.3.142.201:5000/5024221010-backend-kelompok-1:1
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    command: "npm start"
    environment:
      NODE_ENV: development