services:
  app:
    container_name: backend-kelompok-1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    command: "npm start"
    environment:
      NODE_ENV: development