###
GET http://localhost:4000/users

###
GET http://localhost:4000/images

###
GET http://localhost:4000/tags

###
GET http://localhost:4000/users/10

###
GET http://localhost:4000/images/16

###
GET http://localhost:4000/tags/2

###
POST http://localhost:4000/tags
Content-Type: application/json

{
    "name": "Mecha"
}

###
POST http://localhost:4000/users
Content-Type: application/json

{
    "name": "another-example",
    "email": "example@gmail.com",
    "password": "example-pass",
    "birthDate": "02/11/2024",
    "gender": "male",
    "phone": "081234567890",
    "url_profile" : "https://example.com/profile/bobby-fischer"
}

###
POST http://localhost:4000/images
Content-Type: application/json

{
    "name": "test Image path",
    "description": "deskripsi test image path",
    "userId": "10",
    "path": "15.jpg"
}

###
PATCH http://localhost:4000/users/10
Content-Type: application/json

{
    "name": "user_new",
    "email": "user1@gmail.com",
    "password": "secret-pass",
    "brithdate": "02/11/2024",
    "gender": "male",
    "phone": "081234567890"
}

###
PATCH http://localhost:4000/images/16
Content-Type: application/json

{
    "name": "jaket biru",
    "description": "jaket biru editan buat ucits",
    "tags": [2, 3]
}

###
DELETE http://localhost:4000/users/18

###
DELETE http://localhost:4000/images/23

###
DELETE http://localhost:4000/tags/1

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "password": "secret-pass"
}

###
POST  http://localhost:4000/signup
Content-Type: application/json

{
    "email": "uugnup@example.com",
    "password": "test",
    "name": "ij sign up"
}